### ISSUE TITLE
text2sparql.py 

### ISSUE THREAD

**Issue by 489597448** [MeetKai/MK-SQuIT#1]
hello     I did not find the text2sparql file in the model folder

**Comment by jekirl** [comment]
Addding @vinchg who trained it

**Comment by vinchg** [comment]
Please run this script: https://github.com/MeetKai/MK-SQuIT/blob/master/model/setup.sh
```
./setup.sh
```

Or to download it directly from NeMo:
```
wget https://raw.githubusercontent.com/NVIDIA/NeMo/main/examples/nlp/text2sparql/text2sparql.py
```
